### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by gspinaci** [allmaps/allmaps#5]
Hello!

I am trying to install, on my local machine, allmaps. In particular, I am interested in self-hosting an instance of the tile server. 
During the installation, I am getting stuck at this point:

The command:
```
pnpm --filter "@allmaps/tileserver" run dev
```
The log:
```
> @allmaps/tileserver@1.0.0-beta.5 dev /Users/gspinaci/projects/allmaps/apps/tileserver
> npx miniflare dist/worker.js -w -m


> @allmaps/tileserver@1.0.0-beta.5 build
> vite build

vite v2.9.12 building for production...
✓ 5 modules transformed.
[vite:resolve] Failed to resolve entry for package "@allmaps/iiif-parser". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "@allmaps/iiif-parser". The package may have incorrect main/module/exports specified in its package.json.
error during build:
Error: Failed to resolve entry for package "@allmaps/iiif-parser". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "@allmaps/iiif-parser". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (/Users/gspinaci/projects/allmaps/node_modules/.pnpm/vite@2.9.12/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:40945:11)
    at resolvePackageEntry (/Users/gspinaci/projects/allmaps/node_modules/.pnpm/vite@2.9.12/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:40941:9)
    at tryNodeResolve (/Users/gspinaci/projects/allmaps/node_modules/.pnpm/vite@2.9.12/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:40748:20)
    at Object.resolveId (/Users/gspinaci/projects/allmaps/node_modules/.pnpm/vite@2.9.12/node_modules/vite/dist/node/chunks/dep-8f5c9290.js:40556:28)
    at /Users/gspinaci/projects/allmaps/node_modules/.pnpm/rollup@2.75.6/node_modules/rollup/dist/shared/rollup.js:22868:37
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[mf:err] BuildError [1]: Build failed with exit code 1
    at ChildProcess.<anonymous> (/Users/gspinaci/.npm/_npx/46ed1b29b205fa85/node_modules/@miniflare/core/src/plugins/build.ts:77:25)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
BuildError [1]: Build failed with exit code 1
    at ChildProcess.<anonymous> (/Users/gspinaci/.npm/_npx/46ed1b29b205fa85/node_modules/@miniflare/core/src/plugins/build.ts:77:25)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
/Users/gspinaci/projects/allmaps/apps/tileserver:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @allmaps/tileserver@1.0.0-beta.5 dev: `npx miniflare dist/worker.js -w -m`
Exit status 1
```

I entered the commands found in the readme:
```
pnpm install -r
lerna link
```

I am running node v18.9.0, pnpm v7.11.0, lerna 5.18. Moreover, I'm running a M1 max Macbook pro.

Can anyone help me with this? Thanks

**Comment by bertspaan** [comment]
Could you try switching to the `develop` branch and then try the same commands?

**Comment by bertspaan** [comment]
I have seen this error before... I thought I had fixed it.

What happens if you run:

    npx lerna run dev --parallel

**Comment by kgeographer** [comment]
A similar problem re: `vite` - main fails from the `main` branch, then from the `develop` branch, running pnp run init:

```
(base) ➜  allmaps git:(kg/develop) ✗ pnpm run init

> @allmaps/allmaps@ init /Users/karlg/Documents/Repos/allmaps
> pnpm run build:packages && pnpm run check && pnpm run build:ui


> @allmaps/allmaps@ build:packages /Users/karlg/Documents/Repos/allmaps
> pnpm --recursive --filter "./packages/**" run build

Scope: 14 of 26 workspace projects
packages/annotation build$ tsc && pnpm run documentation
└─ Running...
packages/id prebuild$ npm run documentation
│ > @allmaps/id@1.0.0-beta.27 documentation
│ > documentation readme ./dist/index.js --section=API
└─ Running...
packages/iiif-parser build$ tsc
└─ Running...
packages/leaflet build$ vite build && pnpm run documentation
│ vite v5.2.12 building for production...
│ transforming...
│ ✓ 1 modules transformed.
│ x Build failed in 41ms
│ error during build:
│ [commonjs--resolver] Failed to resolve entry for package "@allmaps/render". The package may have incorrect main/module/exports s…
│     at packageEntryFailure (file:///Users/karlg/Documents/Repos/allmaps/node_modules/.pnpm/vite@5.2.12_@types+node@18.19.33/node…
│     at resolvePackageEntry (file:///Users/karlg/Documents/Repos/allmaps/node_modules/.pnpm/vite@5.2.12_@types+node@18.19.33/node…
│     at tryNodeResolve (file:///Users/karlg/Documents/Repos/allmaps/node_modules/.pnpm/vite@5.2.12_@types+node@18.19.33/node_modu…
│     at Object.resolveId (file:///Users/karlg/Documents/Repos/allmaps/node_modules/.pnpm/vite@5.2.12_@types+node@18.19.33/node_mo…
│     at file:///Users/karlg/Documents/Repos/allmaps/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/node-entr…
│     at async PluginDriver.hookFirstAndGetPlugin (file:///Users/karlg/Documents/Repos/allmaps/node_modules/.pnpm/rollup@4.18.0/no…
│     at async resolveId (file:///Users/karlg/Documents/Repos/allmaps/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es…
│     at async ModuleLoader.resolveId (file:///Users/karlg/Documents/Repos/allmaps/node_modules/.pnpm/rollup@4.18.0/node_modules/r…
│     at async Object.resolveId (file:///Users/karlg/Documents/Repos/allmaps/node_modules/.pnpm/vite@5.2.12_@types+node@18.19.33/n…
│     at async PluginDriver.hookFirstAndGetPlugin (file:///Users/karlg/Documents/Repos/allmaps/node_modules/.pnpm/rollup@4.18.0/no…
└─ Failed in 915ms at /Users/karlg/Documents/Repos/allmaps/packages/leaflet
/Users/karlg/Documents/Repos/allmaps/packages/leaflet:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @allmaps/leaflet@1.0.0-beta.35 build: `vite build && pnpm run documentation`
Exit status 1
packages/maplibre build$ vite build && pnpm run documentation
└─ Running...
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.
```

Tried `npm run build` from individual packages: `annotation`, `id` => ok, but `iiif-parser` => numerous errors, all referencing `@allmaps/types` e,g,

`import type { SizeObject, ImageRequest, TileZoomLevel } from '@allmaps/types'`

I hesitate to go further trying things, as `develop` might not even be the branch to work on.

**Comment by bertspaan** [comment]
@kgeographer !!! I've been working on finally fixing the `init` script last week. I'll push my changes tomorrow and I'll report back here!

**Comment by bertspaan** [comment]
Hey @kgeographer, I've updated the init script and pushed the latest changes to the `develop` branch.

- https://github.com/allmaps/allmaps/blob/develop/package.json#L11
- https://github.com/allmaps/allmaps/tree/develop?tab=readme-ov-file#installation

Can you pull the latest develop branch and see if things are now working?
